services:
  - type: web
    name: powercheck-ec
    env: java
    buildCommand: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      chmod +x ./mvnw
      ./mvnw clean install
    startCommand: |
      ./mvnw spring-boot:run
